export const flights = [
  {
    id: '1',
    company: 'Congo Airways',
    logo: '/assets/images/home/congo.jpg',
    name: 'BOING 747-200',
    number: 'B1745',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
    price: '250 USD',
  },
  {
    id: '2',
    company: 'Kenya Airline',
    logo: '/assets/images/home/kenya.jpg',
    name: 'BOING 747-200',
    number: 'B1745',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
    price: '250 USD',
  },
  {
    id: '3',
    company: 'Jambo Jet',
    logo: '/assets/images/home/kenya.jpg',
    name: 'BOING 747-200',
    number: 'B1745',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
    price: '250 USD',
  },
  {
    id: '4',
    company: 'Congo Airways',
    logo: '/assets/images/home/congo.jpg',
    name: 'BOING 747-200',
    number: 'B1745',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
    price: '250 USD',
  },
];
