export const flights = [
  {
    id: '1',
    company: 'Congo Airways',
    name: '51-IFB',
    number: '900',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
  },
  {
    id: '2',
    company: 'CAA',
    name: '51-IFB',
    number: '900',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
  },
  {
    id: '3',
    company: 'Jambo Jet',
    name: '51-IFB',
    number: '900',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
  },
  {
    id: '4',
    company: 'Congo Airways',
    name: '51-IFB',
    number: '900',
    departure: 'KINSHASA',
    arrival: 'GOMA',
    depTime: '14:00',
    arrTime: '16:00',
  },
];
