export const services = [
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#EEF7FF',
    icon: '/assets/images/home/target.png',
    description: 'Recherche et requirement gathering ',
  },
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#FFEBED',
    icon: '/assets/images/home/airplay.png',
    description: 'Recherche et requirement gathering ',
  },
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#E6FFFE',
    icon: '/assets/images/home/database.png',
    description: 'Recherche et requirement gathering ',
  },
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#FFF6EA',
    icon: '/assets/images/home/target.png',
    description: 'Recherche et requirement gathering ',
  },
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#EDFCFF',
    icon: '/assets/images/home/airplay.png',
    description: 'Recherche et requirement gathering ',
  },
  {
    name: '',
    type: '',
    link: '',
    backgroundColor: '#E6E6FF',
    icon: '/assets/images/home/database.png',
    description: 'Recherche et requirement gathering ',
  },
];
